# permissions for end users to edit playops.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: playop-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: play-operator
    app.kubernetes.io/part-of: play-operator
    app.kubernetes.io/managed-by: kustomize
  name: playop-editor-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - playops
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - playops/status
  verbs:
  - get
